name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NEXT_PUBLIC_SANITY_PROJECT_ID: 5bsv02jj

jobs:
  cypress-run:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('./pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Get Cypress cache path
        id: cypress-cache-path
        run: echo "::set-output name=cypress_cache_path::$(npx cypress cache path)"
        working-directory: "packages/tests-e2e"

      - name: Setup Cypress cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.cypress-cache-path.outputs.cypress_cache_path }}
          key: ${{ runner.os }}-cypress-store-${{ hashFiles('./pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-cypress-store-

      - name: Build UI ${{ matrix.node-version }}
        working-directory: packages/ui
        run: pnpm build

      - name: Cypress Run (Production Backend)
        run: pnpm run test:e2e-real:start
#      - name: Cypress Run (Mock Backend)
#        run: pnpm run test:e2e-mock:start
